language: node_js
node_js:
- '7'
before_script:
- yarn build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: JEb1tRrZAuPgcTGhUoq0+kOr8EXOF0vzhbhQivCLjRaOvvaTCtGqPoPmbpLGI1U7ItExJ2/aMiqE8z21DtXdQPLVe2pYWRHXbHIr8IHh/7PDDPMbrdRrgwtf+ta60kk3fcOjdOv90vmf45KPo8Ez5tUo6M1TryIlmYGH931Ljj9F1DrSfiC3DJ/HlKMO6PN2/MBHTy6NvIjBcV2UJNJ/rWgKv1Sibr/ymw31TCOX9LE5PLlJE+PtfGWfsqOzVR4g1lgX+YcjULnIy19u4xlF2a5sny6FzpQKwG6iPsNyvUYv83Wc4i/A0J5UOSVXJe5DSm6eAebNeXNSiRl1gBaCdPuteAcwUji4fbnrFcEpVeKESl+XXcu+HnpKbMRVVvVvOLaduRxUR9Swx83IYbkg+t7z0wP4QDg8omiqIR9bYT4W7+eShoWQ3+PsJk4ZiDzbTWkQmGlvABXY0SbDy2IBfY+wCYTgRb/V7tGPaKgovVEcpAtOEIa7jrQwOa0wpxyabnHwVOd/cyxT6y1lHcN2V4/CLFJ5HtNTNXx4SO4prbp4rJkdJJporDweW2ZgEmJZoy+cZj+kPNY4eGaD9PT3i5Git8c4NhY/T7+ratbFzE2oNnkBF6QV9tvqa96L5VVxUlgeNhNiV27P2n1IUbXu1OagG7bevIGxa8GAT7Li1CM=
  secret_access_key:
    secure: dsyw/TtA7K2jnUE1UsTLfrPLHbKc1k4r+DMLCLbgkGrseeybkRm3xC2NyywBTWXiOYXqhqGDa2OKQZnYPOIsijwj2Tm7EbLvobqSh6PX6Xm5/hsm/SmxNr/UwgaPTdKdf9pJAZLPntu6LhhPe/6ysZx/tTa3IhjeaHzpig0GmxL7ILBQb9G5ZtduzJvA4eSI4ARsBB059HC1/xUqzcal7wqgtpRzk2mLLkxki5XGUQ0xVrt9R6Cx1Fu2LSWQ1QjkeG6zkyFnQtJWHu/iAAY7ZYPxOo4CnDnZt/r2njoy9fSWjp0GHAcXqlPktw/l5ECvertnEH0wGOdwmUFiH/CExPLUdLlKedvSfiutJlAyeu4Swe0snjLewAA9Imr1AWhMWxWXiVrcWbnsoGkoBq6SW4ht6c1yMs4ax8YbKubAAVFfyP1+x4GXOYkDHObNnKH8xBDhwGxp1PS75hMBcbDKCx1sNDuF8ZW3sbKa6YS54LwMVk13n3ArsMkaP/pk0rEk2o4B1SYAXcox3Zkwn37+aaziFR6OuvFFzw2NdhJFtLxYPRgMzN7utQ+crGBRAVHGFBSZd9SHy44Nh59zeA9ytYjGYWL9Q88df/iSrvk6DXoPMMU13mrA7MJY+47ggP/dD7GzMuURSABgMSTfqNKnbZpgn0THolBv+JvA/QnFQz8=
  bucket: gandem.me
  region: eu-west-2
  local-dir: build
  acl: public_read
  on:
    repo: Gandem/personal-website
