language: node_js
node_js:
- '7'
before_script:
- yarn build
deploy:
  skip_cleanup: true
  provider: s3
  access_key_id:
    secure: BhnD/9altGsKZBjbgWVg/ZWgaSMqTnZesn249pVX8qQ4sVJFmWqUf87WfOcONgeB3e17EUBgbSTigEG0rFDJ6VRhVm1KYLMvUy72r2I8uvSvPRto86liHfLd3HKx198XPCcmLRSTgb/P4YWWk4SSoWSy/kbDumI3Isu3N2qVx/weWNaBaz6qLHxMqXSbRU8maLrgDsXFYwSWnCo0Dudm5aHQxlcjoDUuarc/XS7SWZUyKIondOtdnYiRv8B7JPagzKBfbfH+QTBAMhIg4+v4dNcVfVyV30HH+sZTXbkAbsYPOxr5E5Pr1qP7EyvL8hX4N3mYyKgCVvp9y/1+Rpy3UfWo1a4K0C1vnPykPic8UgzV76pUJaLWjV9V1BLLsbFshZG5wyGpJ6iSjCdAAqKDH3naaVI19SBN1Gq7DrY51uO0mzAyusXNJ/0uSnQevRc5+GSQjEnVMkFlxSlCEVvwD37Q8tbm7JWXStHacSsPd351dW3JrpYmxH4iQjGSs5ATyemC5RBnkoC2EoycjtbBKd+95xaPmy6h0xKNjtmM62tc9qTOVK2Z9ooqVVb/CkObL8MvZNLZscBfrAfWna6RzT65KDdJlvFMDEmzvsMae5XajBKJ0wlumiHmiOYvvQ61YECDrCY2Uz5TsvGGLSpcnJuZys4iT2h8UIMBG47peZg=
  secret_access_key:
    secure: hOPM7jBJsznrW2ex4aX+1l4nNLqyb3ioPGVMFteIRcZaTTZuai+PwKPAvJpdxXVUMYEnsfL78MVK4morHcb18FZfSktyjV1MPlKBnot30DJdoVRw9oGlkJoDRBKQFlcErWYSsUhH6d6/9Pw63SrTlVKY6ZcIab6AYOEIyKZQGu+lC+Y5PoKO151vckuYsPNDK4ovacvBLb3y2qQ9OvT+OxerbXcQ7s5EPgtLFLjRGrBsUenSEkuv7RDHmZre+NOXjgigr2Lof+0OOFLfLNBpSf32FIasBZwu1K2x1M4czFcxQ8zO+xgErDgksOUqGsAEZGRwBR8muxrTmLHx/Aj9IbyzFWYz8JrrFkZWhv1r/o8oEOCIyFLvaEBHnDjlJb99zdnS1FC4tvupkRRbPmNrVGvbc525j/NxLei7WjrSgo0Mu3d3vXXrnqzOObHFC/4K9PG5v9Hs8IfHljs2RoEGccuhpSRwCQeFB9X8PJuwXTMeZYq8YrNgOvDZ0LRQsnY/vGyV0RPqu0GDtynhsRbIJ7NbVq6WstAIaqYv6IB7qJZ0kvvhZT19dLaN9LtvHdpaXS7SgNTcbYqJf9sNZoQxhL4D+M/UwhrOKZGsCTqN2B8KhR4jRAdVp0h9ZXm6Up5ixyybxEjcm0tUWrZFtinsXcSvAv+nyy3LoHGJcbOKQyU=
  bucket: gandem.me
  region: eu-west-2
  local-dir: build
  acl: public_read
  on:
    repo: Gandem/personal-website
